#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from rviz_plugin_camerapos.rviz_plugin_camerapos import RvizPlguinCamerapos
from rqt_gui.main import Main

plugin = 'rviz_plugin_camerapos'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))